package io.github.aimtone.tentacolous.schema;

import io.github.aimtone.tentacolous.model.DbOperation;
import io.github.aimtone.tentacolous.registry.ListenerDefinition;
import org.springframework.jdbc.core.JdbcTemplate;

import java.util.List;
import java.util.Locale;
import java.util.stream.Collectors;

public class OracleDialect implements DatabaseDialect {

    @Override
    public boolean supports(String name) {
        return name != null && name.toLowerCase(Locale.ROOT).contains("oracle");
    }

    @Override
    public void createEventInfrastructure(JdbcTemplate jdbc, String table) {
        String ddl = "CREATE TABLE " + table + " (id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                + "entity_name VARCHAR2(255) NOT NULL, operation VARCHAR2(20) NOT NULL, payload CLOB NOT NULL, "
                + "old_payload CLOB NULL, record_key VARCHAR2(4000) NULL, status VARCHAR2(20) DEFAULT 'PENDING' NOT NULL, "
                + "processed NUMBER(1) DEFAULT 0 NOT NULL, attempts NUMBER(10) DEFAULT 0 NOT NULL, last_error CLOB NULL, "
                + "created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, processing_started_at TIMESTAMP NULL, "
                + "processed_at TIMESTAMP NULL)";
        jdbc.execute("BEGIN EXECUTE IMMEDIATE '" + DialectSupport.escapeLiteral(ddl)
                + "'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;");
    }

    @Override
    public void validateEventInfrastructure(JdbcTemplate jdbc, String table) {
        Integer count = jdbc.queryForObject("SELECT COUNT(*) FROM user_tables WHERE table_name = UPPER(?)",
                Integer.class, DialectSupport.unqualifiedName(table));
        if (count == null || count == 0) throw new IllegalStateException("Missing Tentacolous event table: " + table);
    }

    @Override
    public void createTrigger(JdbcTemplate jdbc, String eventTable, ListenerDefinition listener) {
        List<String> columns = oracleColumns(jdbc, listener);
        DbOperation operation = listener.getOperation();
        String row = operation == DbOperation.DELETE ? ":OLD" : ":NEW";
        String payload = json(columns, row);
        String oldPayload = operation == DbOperation.UPDATE ? json(columns, ":OLD") : "NULL";
        jdbc.execute("CREATE OR REPLACE TRIGGER " + triggerName(listener.getTableName(), operation) + " AFTER "
                + operation.name() + " ON " + listener.getTableName() + " FOR EACH ROW BEGIN INSERT INTO "
                + eventTable + " (entity_name, operation, payload, old_payload, record_key) VALUES ('"
                + DialectSupport.escapeLiteral(listener.getEntityName()) + "', '" + operation.name() + "', "
                + payload + ", " + oldPayload + ", TO_CHAR(" + row + "." + listener.getRecordKeyField() + ")); END;");
    }

    private List<String> oracleColumns(JdbcTemplate jdbc, ListenerDefinition listener) {
        String schema = DialectSupport.schemaName(listener.getTableName());
        String sql = schema == null
                ? "SELECT column_name FROM user_tab_columns WHERE table_name = UPPER(?) ORDER BY column_id"
                : "SELECT column_name FROM all_tab_columns WHERE table_name = UPPER(?) AND owner = UPPER(?) ORDER BY column_id";
        Object[] args = schema == null
                ? new Object[]{DialectSupport.unqualifiedName(listener.getTableName())}
                : new Object[]{DialectSupport.unqualifiedName(listener.getTableName()), schema};
        var excluded = listener.getExcludedColumns().stream()
                .map(value -> value.toLowerCase(Locale.ROOT)).collect(Collectors.toSet());
        List<String> columns = jdbc.query(sql, (rs, row) -> rs.getString(1), args).stream()
                .filter(column -> !excluded.contains(column.toLowerCase(Locale.ROOT))).toList();
        if (columns.isEmpty()) {
            throw new IllegalStateException("No payload columns found for table " + listener.getTableName());
        }
        return columns;
    }

    private String json(List<String> columns, String row) {
        return columns.stream().map(c -> "'" + DialectSupport.escapeLiteral(c.toLowerCase(Locale.ROOT))
                        + "' VALUE " + row + "." + c)
                .collect(Collectors.joining(", ", "JSON_OBJECT(", " RETURNING CLOB)"));
    }

    @Override
    public String selectPendingEventsSql(String table) {
        return "SELECT id, entity_name, operation, payload, old_payload, record_key FROM ("
                + "SELECT id, entity_name, operation, payload, old_payload, record_key FROM " + table
                + " WHERE status = 'PENDING' ORDER BY id) WHERE ROWNUM <= ?";
    }

    @Override
    public String selectHistorySql(String table) {
        return "SELECT payload FROM " + table
                + " WHERE entity_name = ? AND id < ? AND operation IN ('INSERT', 'UPDATE') AND record_key = ? ORDER BY id";
    }

    @Override
    public Object[] selectHistoryArguments(String entityName, Long eventId, String recordKey, String field) {
        return new Object[]{entityName, eventId, recordKey};
    }


    @Override
    public String trueLiteral() { return "1"; }
}
